### MakeMeMod
#

# Configuration Version
configVer: '1.0'

# ----- Standard plugin features

# Broadcast group changes to all players
broadcast-all: 'true'

# Broadcast group changes to specific groups
broadcast-group: 'false'

# Groups to broadcast to
broadcast-targets:
- 'Admin'
- 'Moderators'

# General Permission changes or world specific?
general-perm-changes: 'false'

# ----- Group Change Commands
#
# Customize Group Change Commands in form of
# command: GroupTheyAreIn,GroupTheyShouldBeIn
#
alias-list:
    mod: Builder,Moderators
    admin: Builder,Admins
    