### MakeMeMod
#

# Configuration Version
configVer: '1.0'

# ----- Standard plugin features

# Broadcast group changes to all players
broadcast-all: 'true'

# Broadcast group changes to specific groups
broadcast-group: 'false'

# Groups to broadcast to
broadcast-targets:
- 'Admin'
- 'Moderators'

# ----- Group Change Commands
#
# Customize Group Change Commands in form of
# command: Group
#
alias-list:
- mod:Moderators
- admin:Admins