name: MakeMeMod
main: org.simiancage.bukkit.makememod.MakeMeMod
version: 1.2
author: DonRedhorse
description: Changing Groups back and forth
softdepend: [PermissionsEx,Vault]
commands:
    mmm:
        description: Used as fallback for aliases or to issue reload command
        permission: mmm.command
        usage: /<command> [Alias|reload]
permissions:
    mmm.*:
        description: Gives access to all MakeMeMod commands
        children:
            mmm.reload: true
            mmm.command: true
    mmm.reload:
        description: Allows reloading of MakeMeMod config
        default: OP
    mmm.command:
        description: Allows executing of ConfigMMM command
        default: OP
