name: MakeMeMod
main: org.simiancage.bukkit.makememod.MakeMeMod
version: 0.1
author: DonRedhorse
commands:
    mmm:
        description: Used as fallback for aliases or to issue reload command
        permission: MMM.command
        usage: /<command> [Alias|reload]
permissions:
    MMM.*:
        description: Gives access to all MakeMeMod commands
        children:
            MMM.reload: true
    MMM.reload:
        description: Allows reloading of MakeMeMod config
        default: OP
    MMM.command:
        description: Allows executing of MMM command
        default: OP
